baseurl = "/"
languageCode = "en-US"
title = "Jose Lucas Safanelli"
disqusShortname = "zecojls"
googleAnalytics = "UA-91263647-1"
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "José Lucas Safanelli"
  description = "Blog pessoal"
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "zecojls"
  Email         = "zecojls@gmail.com"
  LinkedIn      = "joselucassafanelli"

## Main Menu
##[[menu.main]]
##  name = "posts"
##  identifier = "posts"
##  weight = 200
##  url = "/posts/"
##[[menu.main]]
##  name = "sobre"
##  identifier = "sobre"
##  weight = 300
##  url = "/about/"
