---
title: About me
author: José Lucas Safanelli
date: '2018-02-13'
---

I'm from Canoinhas, SC, Brazil. I'm 24 years old, a soccer fan (to watch and play) and a beer appreciater (in the future I wanna start to produce my own beer). I currently live at Piracicaba - SP with some friends.

My native language is portuguese and I decided to write things in this blog in both portuguese and english. I apologize if my english is not fluent, but I believe blogging here can help me to improve it.

About my interests and motivations, everything started when I took a technical course in agriculture at the same time of the high school. I really enjoyed that and I decided to continue studying agronomy.

As a undergraduate student, the use of technology and information in agriculture has aroused me a great interest for a possible working area. I also liked the academia and had some fellowships in that period, which helped me to continue as a graduate student nowadays.

Currently, I'm taking the doctorate (Agronomy - Soils and Plant Nutrition) at University of São Paulo, and I intend to continue doing research or working on these subjects in the future.

My main interests are related to the application of technology and data science in soil research, agricultural and environmental issues, using the R programming language, and free and open source softwares (mainly GIS).

If you are interested, you can access additional information about me on my [linkedin](https://www.linkedin.com/in/joselucassafanelli) profile, or by the following links

+ [OrcID](http://orcid.org/0000-0001-5410-5762)
+ [Currículo Lattes](http://lattes.cnpq.br/0464981449599291)


&#128077;&#127995;
